[workspace]
members = [
    "eventually",
    "eventually-core",
    "eventually-postgres",
    "eventually-redis",
    "eventually-event-store-db",
    "eventually-util",
    "eventually-app-example"
]
